// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, client, developerToken;

  Evernote = require('evernote').Evernote;

  developerToken = process.env.DeveloperToken;

  client = new Evernote.Client({
    token: developerToken
  });

  module.exports = client;

}).call(this);

//# sourceMappingURL=evernote.js.map
